_format_version: "1.1"

services:
  - name: app-shell
    url: http://host.docker.internal:8082
    routes:
      - name: app-shell-routing
        paths:
          - /
  - name: todo-list-api
    url: http://host.docker.internal:8003/todoList
    routes:
      - name: todo-list-api-routing
        paths:
          - /todoList
  - name: todo-list-component
    url: http://host.docker.internal:8083/todoListComponent
    routes:
      - name: todo-list-component-routing
        paths:
          - /todoListComponent
